### ISSUE TITLE
The gold stars aren't displayed in the "All Semesters" view

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci/senior-seminar#50]
The "All Semesters" view doesn't include the gold stars like the specific semester views do. It would be nice if "All Semesters" also included them, since it's easier to link to "All Semesters" in Canvas assignments instead of having a link to a specific semester that has to be updated each term.

**Comment by floogulinc** [comment]
I think the reason I decided not to display them on the listing of all seminars page is because some semesters didn't have the concept of gold stars for slides, papers, or both and displaying them on the list of all semesters would imply some were eligible for stars that actually weren't. But I have created a PR for this if you want to add them #51.

**Comment by NicMcPhee** [comment]
Thanks – I appreciate that. I do realize that we haven't been super consistent about stars over the history of the course, but I do think we've _usually_ got them in recent years, which is what most current students are mostly likely to look at/interact with. I'll look at the PR, and probably bring it in.

**Comment by elenam** [comment]
We probably can mark semesters that didn't have papers/presentations evaluated for gold stars, especially in recent years. This doesn't solve the issue that including them in All Seminars might be misleading, but at least it would add transparency.
